# ----------- Build Stage ------------
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Build Vite app (this uses .env.production automatically)
RUN npm run build


# ----------- Deploy Stage ------------
FROM nginx:alpine

# Copy built frontend to nginx hosting directory
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port
EXPOSE 5173

# Replace default NGINX config to allow custom port
RUN sed -i 's/listen 80;/listen 5173;/g' /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
